<?php
namespace App\Repositories;

use LaravelRocket\ServiceAuthentication\Repositories\ServiceAuthenticationRepositoryInterface;

interface UserServiceAuthenticationRepositoryInterface extends ServiceAuthenticationRepositoryInterface
{
}
